src/graphql/__tests__/entries.test.ts

fix current unit tests based on changes in #33

chore: fix unit tests [TOL-1022]

---

README.md

Add Gatsby integration documentation

docs: add section about gatsby

---

src/field-tagging.ts
src/graphql/__tests__/entries.test.ts
src/graphql/assets.ts
src/graphql/entries.ts
src/index.ts
src/live-updates.ts
src/types.ts
src/utils.ts
vite.config.ts

Complex field support for graphql live updates

feat: complex field support for live preview iframe

---

README.md
src/field-tagging.ts
src/graphql/__tests__/entries.test.ts
src/graphql/assets.ts
src/graphql/entries.ts
src/graphql/utils.ts
src/index.ts
src/live-updates.ts
src/react.ts
src/types.ts
src/utils.ts

Initial implementation of the restoration of updates after navigation (currently disabled) and some cleanups

chore(live-updates): prepare restore changes after navigation [TOL-1071]

---

src/live-updates.ts

fix(live-updates): cannot read id of undefined

---

src/constants.ts
src/field-tagging.ts
src/graphql/__tests__/entries.test.ts
src/graphql/entries.ts
src/index.ts
src/types.ts
src/utils.ts

Optimize typings and structure for the send messages, so we can reuse the type on the side

fix(types): better typing for the send messages

---

src/field-tagging.ts
src/graphql/__tests__/entries.test.ts
src/graphql/entries.ts
src/graphql/utils.ts
src/helpers/field.ts
src/helpers/index.ts
src/helpers/utils.ts
src/helpers/uuid.ts
src/index.ts
src/live-updates.ts
src/react.ts
src/rest/__tests__/entries.test.ts
src/rest/__tests__/fixtures/contentType.json
src/rest/__tests__/fixtures/dataFromPreviewApp.json
src/rest/__tests__/fixtures/updateFromEntryEditor.json
src/rest/entries.ts
src/rest/index.ts
src/tests/index.spec.ts
src/tests/init.spec.ts
src/tests/live-updates.spec.ts
src/tests/utils.spec.ts
src/utils.ts

- Add support for Live Updates REST endpoint
- Rename variables in GraphQL and LiveUpdates class to make it more descriptive

feat: Live Updates REST endpoint support

---

src/__tests__/liveUpdates.spec.ts
src/liveUpdates.ts
src/types.ts

Send a message to the editor once there is a subscription and if it is using GQL or REST

feat: notifiy the editor about subscriptions [TOL-1059]

---

src/__tests__/liveUpdates.spec.ts
src/helpers/utils.ts
src/liveUpdates.ts

- Activate persisting data across page navigation
- Ensure callback is only called for active subscriptions in restore method
- Make restore method work with Arrays

feat: keep info after navigating [TOL-1080]

---

README.md
src/__tests__/init.spec.ts
src/__tests__/react.spec.ts
src/graphql/__tests__/entries.test.ts
src/graphql/entries.ts
src/index.ts
src/liveUpdates.ts
src/react.ts
src/types.ts

This should give the end user the ability to disable features on the live preview sdk

feat: disable live preview features [TOL-1072]

---

README.md
src/__tests__/init.spec.ts
src/index.ts

- remove the alpha state note
- add a link to the official developer documentation

chore(docs): remove alpha and add official docs

---

src/__tests__/init.spec.ts
src/__tests__/inspectorMode.spec.ts
src/__tests__/liveUpdates.spec.ts
src/__tests__/react.spec.tsx
src/graphql/__tests__/entries.test.ts
src/graphql/__tests__/utils.test.ts
src/graphql/entries.ts
src/graphql/utils.ts
src/index.ts
src/inspectorMode.ts
src/liveUpdates.ts
src/react.tsx
src/rest/entities.ts
src/types.ts

- add functionality for nested reference updates
- more explained error messages for required params on init and provider
- add more tests / update locale handling in tests
- typing improvments
- remove false positives for unrecognized fields
Tickets:
- https://contentful.atlassian.net/browse/TOL-1181
- https://contentful.atlassian.net/browse/TOL-1172

fix(graphql): support for adding references inside nested references [TOL-1181]

---

examples/remix/.env.example
examples/remix/.eslintrc
examples/remix/.gitignore
examples/remix/README.md
examples/remix/app/components/preview-banner.tsx
examples/remix/app/entry.client.tsx
examples/remix/app/entry.server.tsx
examples/remix/app/root.tsx
examples/remix/app/routes/$slug.tsx
examples/remix/app/routes/api/exit-preview.ts
examples/remix/app/routes/api/preview.ts
examples/remix/app/routes/index.tsx
examples/remix/app/utils/parse-cookie.server.ts
examples/remix/app/utils/preview-mode.server.ts
examples/remix/lib/contentful.server.ts
examples/remix/package.json
examples/remix/remix.config.js
examples/remix/tsconfig.json

Add a simple remix example with live preview

feat: remix example [TOL-1177]

---

src/types.ts

fix(types): optimize types for usage with contentful client SDK

---

package.json
src/helpers/utils.ts
yarn.lock

Reordered semantic packaged to fix versioning issue

fix: update package order

---

examples/gatsby/.env.EXAMPLE
examples/gatsby/.gitignore
examples/gatsby/README.md
examples/gatsby/gatsby-browser.tsx
examples/gatsby/gatsby-config.ts
examples/gatsby/gatsby-node.ts
examples/gatsby/package.json
examples/gatsby/src/pages/404.tsx
examples/gatsby/src/pages/index.tsx
examples/gatsby/src/templates/post.tsx
examples/gatsby/tsconfig.json

- live preview SDK example with gatsby

docs: gatsby example [TOL-1176]

---

src/graphql/entries.ts
src/types.ts

Fix embedded entries in rich text with GraphQL
**Before**:
https://github.com/contentful/live-preview/assets/22968325/32a9a88c-eab8-4cc6-9e21-252217391a04
**After**:
https://github.com/contentful/live-preview/assets/22968325/7f370f5c-0a2e-436d-9367-f2ec87801f74

fix: embedded entries rich text [TOL-1197]

---

README.md
package.json
src/__tests__/liveUpdates.spec.ts
src/graphql/__tests__/entries.test.ts
src/graphql/__tests__/queryUtils.test.ts
src/graphql/__tests__/utils.test.ts
src/graphql/assets.ts
src/graphql/entries.ts
src/graphql/queryUtils.ts
src/graphql/utils.ts
src/helpers/field.ts
src/helpers/resolveReference.ts
src/index.ts
src/liveUpdates.ts
src/react.tsx
src/rest/__tests__/entities.test.ts
src/rest/__tests__/fixtures/contentType.json
src/rest/entities.ts
src/types.ts
yarn.lock

Provide support for GraphQL aliases by parsing the provided query (DocumentNode)

feat(graphql): support for graphql aliases [TOL-1115]

---

src/rest/entities.ts

Fix embedded entries in rich text with REST

fix: embedded entries rich text REST [TOL-1197]

---

README.md
examples/gatsby/README.md
examples/gatsby/package.json
examples/nextjs-graphql/package.json
examples/nextjs-rest/package.json
examples/remix/package.json

- update examples to latest SDK version
- add note on active development of Gatsby support

docs: update examples and mention gatsby development

---

package.json
src/rest/__tests__/constants.ts
src/rest/__tests__/entities.test.ts
src/rest/__tests__/fixtures/data.ts
src/rest/__tests__/utils.ts
src/rest/entities.ts
vite.config.ts
yarn.lock

- fixes an issue with entry-hyperlink and asset-hyperlink not resolving correctly
- the previous PR (https://github.com/contentful/live-preview/pull/181) introduced tests, but these were false positives.. 😬 I refactored the tests and now they should capture all the possible embedded entries (including entry-hyperlink and asset-hyperlink)

fix: hyperlink references in REST and update tests [TOL-1290]

---

src/helpers/utils.ts
src/index.ts
src/types.ts

add functionality to get debug information on the message flow for better troubleshooting

chore: add debug information and locale to messages

---

src/__tests__/liveUpdates.spec.ts
src/liveUpdates.ts

Don't know why it was not complaining on the previous PR, but I get a error locally about a missing property - let's adjust this.

chore: adjust type error

---

src/constants.ts
src/rest/__tests__/entities.test.ts
src/rest/entities.ts

Fixing circular references by adding max depth in REST API

fix: circular references max depth REST [TOL-1260]

---

packages/live-preview-sdk/package.json
packages/live-preview-sdk/src/__tests__/fixtures/assetFromEntryEditor.json
packages/live-preview-sdk/src/__tests__/fixtures/pageInsideCollectionFromEntryEditor.json
packages/live-preview-sdk/src/__tests__/liveUpdates.spec.ts
packages/live-preview-sdk/src/__tests__/resolveReference.spec.ts
packages/live-preview-sdk/src/graphql/__tests__/asset.test.ts
packages/live-preview-sdk/src/graphql/__tests__/entries.test.ts
packages/live-preview-sdk/src/graphql/__tests__/fixtures/entry.json
packages/live-preview-sdk/src/graphql/assets.ts
packages/live-preview-sdk/src/graphql/entries.ts
packages/live-preview-sdk/src/helpers/entities.ts
packages/live-preview-sdk/src/helpers/field.ts
packages/live-preview-sdk/src/helpers/resolveReference.ts
packages/live-preview-sdk/src/helpers/utils.ts
packages/live-preview-sdk/src/index.ts
packages/live-preview-sdk/src/liveUpdates.ts
packages/live-preview-sdk/src/messages.ts
packages/live-preview-sdk/src/rest/__tests__/entities.test.ts
packages/live-preview-sdk/src/rest/__tests__/fixtures/data.ts
packages/live-preview-sdk/src/rest/__tests__/fixtures/updateAssetFromEntryEditor.json
packages/live-preview-sdk/src/rest/__tests__/fixtures/updateFromEntryEditor.json
packages/live-preview-sdk/src/rest/__tests__/utils.ts
packages/live-preview-sdk/src/rest/entities.ts
packages/live-preview-sdk/src/types.ts
packages/visual-sdk/package.json

The editor will now resolve the locale and also handles the fallback logic of locales.
This adopts the SDK to work with the new structure

feat: support fallback locales

---

packages/live-preview-sdk/src/constants.ts

Adjust the max depth of entry resolution like discussed in the slack thread

fix(live-updates): support deeper nested entries

---

README.md
packages/live-preview-sdk/src/__tests__/index.spec.ts
packages/live-preview-sdk/src/__tests__/liveUpdates.spec.ts
packages/live-preview-sdk/src/__tests__/validation.spec.ts
packages/live-preview-sdk/src/helpers/utils.ts
packages/live-preview-sdk/src/helpers/validation.ts
packages/live-preview-sdk/src/index.ts
packages/live-preview-sdk/src/inspectorMode.ts
packages/live-preview-sdk/src/liveUpdates.ts
packages/live-preview-sdk/src/messages.ts

- Provide more useful information for the status modal inside the live preview editor

fix(live-preview): provide better information for status modal

---

examples/remix/README.md

Updating remix example documentation related to issue: https://github.com/contentful/live-preview/issues/266

chore: update readme of remix example

---

README.md
examples/vanilla-js/.env.example
examples/vanilla-js/.gitignore
examples/vanilla-js/README.md
examples/vanilla-js/app.js
examples/vanilla-js/index.html
examples/vanilla-js/package.json

- add a vanilla js example project with the SDK installed
- update the docs
Fixes:
- https://github.com/contentful/live-preview/issues/217
- https://github.com/contentful/live-preview/issues/152

docs: vanilla js example [TOL-1416]

---

packages/live-preview-sdk/src/inspectorMode/index.ts

Adding resize handling for entry saves and updates

chore: adding resizing handler for entry updates [TOL-1644]

---

README.md
packages/live-preview-sdk/src/__tests__/react.spec.tsx
packages/live-preview-sdk/src/index.ts
packages/live-preview-sdk/src/inspectorMode/types.ts
packages/live-preview-sdk/src/inspectorMode/utils.ts
packages/live-preview-sdk/src/messages.ts
packages/live-preview-sdk/src/react.tsx
packages/live-preview-sdk/src/types.ts

Adding asset editor field tagging

feat: adding support for asset editor field tagging [TOL-1683]

---

packages/visual-sdk/src/store/EntityStore.ts

fix: better logging for unresolved entity link [SPA-1711]

---

packages/live-preview-sdk/src/inspectorMode/utils.ts
packages/live-preview-sdk/src/rest/__tests__/entities.test.ts
packages/live-preview-sdk/src/rest/entities.ts

- Handle removal of rich text field values in REST
- Remove console.log
related issue: https://github.com/contentful/live-preview/issues/434

fix: handle empty rich text field [TOL-1708]

---

.contentful/vault-secrets.yaml

adding Package read policy for GH packages migration

feat: add package read policy [TOL-1702]

---

.circleci/config.yml
.eslintrc.cjs
.github/dependabot.yml
package.json
packages/live-preview-sdk/src/__tests__/csm.spec.ts
packages/live-preview-sdk/src/__tests__/index.spec.ts
packages/live-preview-sdk/src/__tests__/inspectorMode.spec.ts
packages/live-preview-sdk/src/__tests__/saveEvent.spec.ts
packages/live-preview-sdk/src/__tests__/validation.spec.ts
packages/live-preview-sdk/src/csm/index.ts
packages/live-preview-sdk/src/helpers/utils.ts
packages/live-preview-sdk/src/helpers/validation.ts
packages/live-preview-sdk/src/rest/entities.ts
yarn.lock

feat: setup gh packages [TOL-1702]

---

packages/content-source-maps/src/encode.ts
packages/content-source-maps/src/encodeSourceMap.ts

- use stega combine method instead of encode
- combine method already does date and URL check
- combine will place the hidden string value at the end instead of the start of the string

feat: use stega combine method [TOL-1844]

---

packages/live-preview-sdk/src/inspectorMode/__tests__/getAllTaggedElements.test.ts
packages/live-preview-sdk/src/inspectorMode/utils.ts

- If multiple elements have the same information their wrapper element is tagged instead (typical case: RichText)
- Support tagging for images (I added an `img` for the test and wondered why it's not working 🙈 )
- Ignore invisible tags from being tagged (information in the head, script)
- Use the new `combine` fn also for the test setup

fix(content-sourcemap): tag only the wrapper around richtext

---

packages/content-source-maps/src/encodeSourceMap.ts

exporting utilities for editor interfaces control with selective Content Source Map generation, allowing exclusion of certain widgets during live updates

feat: export editor interface utils [TOL-1967]

---

README.md

docs: add limitations

---

packages/content-source-maps/src/__tests__/graphql.spec.ts

This was fixed in previous work & we updated the tests to reflect this use case

test(content-source-maps): add test for hyperlinks in richtext []

---

packages/live-preview-sdk/src/__tests__/init.spec.ts
packages/live-preview-sdk/src/__tests__/inspectorMode.spec.ts
packages/live-preview-sdk/src/__tests__/react.spec.tsx
packages/live-preview-sdk/src/index.ts
packages/live-preview-sdk/src/inspectorMode/index.ts
packages/live-preview-sdk/src/inspectorMode/types.ts
packages/live-preview-sdk/src/types.ts

fix(inspectorMode): more accurate outlines [TOL-1718]

---

packages/live-preview-sdk/src/react.tsx

When using `"strictNullChecks": false` in `tsconfig.json` using a project with the live preview SDK and inspector mode, you would get this error:
```
Object literal may only specify known properties, and 'fieldId' does not exist in type '({ entryId: string; } | { assetId: string; }) & Pick<LivePreviewProps, "locale" | "space" | "environment">'.
```
I simplified the `GetInspectorModeProps` type which fixes this issue

fix: inspector mode types [ZEND-5004]

---

packages/live-preview-sdk/src/react.tsx

Simplifying inspector mode types

fix: simplify inspector mode types

---

packages/content-source-maps/src/__tests__/graphql.spec.ts
packages/content-source-maps/src/__tests__/rest.spec.ts
packages/content-source-maps/src/graphql/encodeGraphQLResponse.ts
packages/content-source-maps/src/rest/encodeCPAResponse.ts
packages/content-source-maps/src/utils.ts

adjusting the changes made in the graphql api & CPA. This will be a breaking change & will be reflected as such in the squash commit

feat: add-adjustments-to-pointers [TOL-2036]

---

packages/live-preview-sdk/src/index.ts

follow up on https://github.com/contentful/live-preview/pull/821

fix(import/export): import version correctly on the remaining place []

---

README.md

https://discord.com/channels/1030176999471321129/1268975295667372073

docs(known issues): add genereal block about embedding into another iframe than contentful app []

---

packages/content-source-maps/src/graphql/encodeGraphQLResponse.ts
packages/content-source-maps/src/rest/encodeCPAResponse.ts

- replace console error with warning
- make error more clear

fix: console warnings of missing pointers in Content Source Maps entry []

---

examples/next-app-router-ssr/app/components/post-layout.tsx
examples/next-app-router-ssr/lib/api-graphql.ts

updating the ssr example to show how to tag a nested reference

chore: update ssr example with refs []

---

packages/live-preview-sdk/package.json
yarn.lock

Reverts contentful/live-preview#980

revert: "chore: update react version"

---

examples/content-source-maps-cpa/README.md
examples/content-source-maps-cpa/src/pages/index.tsx
examples/content-source-maps-graphql/README.md
examples/content-source-maps-graphql/app/page.tsx
examples/content-source-maps-graphql/components/PostsRenderer.tsx
packages/content-source-maps/README.md

- Add section on combining live updates + content source maps
- Update example
Fixes: https://github.com/contentful/live-preview/issues/1100

docs: add explanation about CSM and live updates [TOL-2936]

---

packages/content-source-maps/package.json
packages/content-source-maps/src/richText.ts
yarn.lock

fix(content-source-maps): improve types and add missing package []
