contentful/live-preview

- package.json
- src/features/tagging/getLivePreviewProps.spec.ts
- src/features/tagging/getLivePreviewProps.ts
- src/features/tagging/index.tsx
- src/index.tsx
- yarn.lock
Adding initial tagging functionality
> fix: adding vitest and initial tagging function [TOL-909]

- src/graphql/__tests__/entries.test.ts
- src/graphql/__tests__/fixtures/entry.json
- src/graphql/assets.ts
- src/graphql/entries.ts
- src/graphql/utils.ts
- src/live-updates.ts
- src/types.ts
- Primitive fields bug fixes: We only want to update the fields that need to be updated and save the updates in a Map so we check if we already had some changes before entityChanged fires again
- Rrich text GraphQL
- Multi ref field changes (position + removal)
> fix: live updates [TOL-1000, TOL-1022]

- src/graphql/__tests__/entries.test.ts
- src/graphql/entries.ts
When resorting we can get an issue where graphql properties are lost. This makes sure that if we have them we merge them with the updated order etc.
> fix: merging graphql properties that we already have [TOL-1079]

- README.md
- src/liveUpdates.ts
Currently if a error occurs, it goes wild - let's handle it to write the information in the debug.error function and not crashes the client application
> chore(live-updates): handle merge errors []

- src/graphql/assets.ts
Videos doesn't have the width and height information, so therefor they are currently not updating correctly.
This can lead to issues on the app side as the returned information are not the same as expected.
> fix(live-updates): add support for videos, currently they are not processed correctly [TOL-1173]

- src/react.tsx
We had a bug with the inspector props & the locale was treated as a required prop for inspector mode even after the locale optimisation was added. this should fix that
> fix: conditionally check correct props [NONE]

- src/react.tsx
The type mapping for GetInspectorModeProps was resulting in the locale being set to required when it shouldn't be
> chore: exclude locale from type mapping [NONE}

- src/__tests__/inspectorMode.spec.ts
- src/__tests__/liveUpdates.spec.ts
- src/__tests__/resolveReference.spec.ts
- src/__tests__/validation.spec.ts
- src/graphql/__tests__/entries.test.ts
- src/graphql/entries.ts
- src/helpers/index.ts
- src/helpers/resolveReference.ts
- src/helpers/utils.ts
- src/helpers/validation.ts
- src/index.ts
- src/inspectorMode.ts
- src/liveUpdates.ts
- src/rest/__tests__/entities.test.ts
- src/rest/entities.ts
- src/types.ts
1. We have the case that not everything is resolved correctly on nested references
2. We would need to return only partial data to resolve then in the next step the reference correctly
This two cases can lead to a broken UI if the handling of data is not checking things very precise on their part.
Let's make the entity not known a promise and build everything async.
> fix(references): move to promises to optimize loading behaviour

- src/graphql/entries.ts
- src/rest/entities.ts
Handle two cases where `value` could be `null` and `value.sys.id` would throw an error instead of doing updates.
Related to #161
> fix(live-updates): optimize null handling []

- src/__tests__/liveUpdates.spec.ts
- src/graphql/__tests__/entries.test.ts
- src/graphql/__tests__/queryUtils.test.ts
- src/graphql/entries.ts
- src/graphql/queryUtils.ts
- src/liveUpdates.ts
- Fields were not updated for GraphQL if the entry was newly generated.
This was because of the `isRelevantField` implementation, now it updates every field, which produces some adjustments in the tests.
- "cannot read content of null" due a missing `null` type on `richTextNode`
> fix(graphql): fields not updating when creating a new entry [TOL-1251]

- src/rest/__tests__/entities.test.ts
- src/rest/entities.ts
The updateRef function inside entities.ts for REST was not specifically handling 'RichText'.
It was only checking if the field's value is an object or an array of objects with sys property (indicating it's a reference to another Contentful entity), and then either updates a single reference field (updateSingleRefField) or multiple reference fields (updateMultiRefField). We also handle primitive fields, which just replaces the entity with the update (which is what happens currently with the Rich Text field). So it did not have specific logic to handle 'RichText' and its embedded entries.
> fix: updateRef embedded entries REST [TOL-1263]

- src/graphql/entries.ts
- src/rest/entities.ts
- fix an issue with entry and asset hyperlinks with graphql (fixes https://github.com/contentful/live-preview/issues/179)
- use rich text types package to determine the types
- add missing debug warn in REST version when we are handling an unknown embedded entry type
https://github.com/contentful/live-preview/assets/22968325/b792f2b2-64e5-4c6a-bc87-e6e4894c605a
> fix: graphql embedded entries hyperlinks [TOL-1262]

- .github/dependabot.yml
- packages/live-preview-sdk/package.json
- packages/live-preview-sdk/vite.config.ts
- yarn.lock
The adjustment on the config was not working, looks like through the cache I could still re-produce it correctly locally :( 
Downgrading the vite plugin works so let's do that first as we want to migrate to pure swc anyways
> fix(sdk): re-publish types

- packages/live-preview-sdk/package.json
- packages/live-preview-sdk/src/liveUpdates.ts
- packages/live-preview-sdk/src/react.tsx
- packages/live-preview-sdk/src/rest/__tests__/entities.test.ts
- packages/live-preview-sdk/src/rest/entities.ts
- We were using the`useDeepCompareEffectNoCheck` package, which has a dependency on dequal package. Dequal has an issue with infinite loops in circular references: https://github.com/lukeed/dequal/issues/19 . I removed this package in favour of the is isEqual package from lodash. This one seems to work better with circular references.
- Even with the previously introduced depth limitation for REST (https://github.com/contentful/live-preview/pull/195), you could still encounter infinite loops if an entity links to itself directly or indirectly. Now, when a circular reference is detected, it does not update the reference further. Instead, it returns the the already updated reference from the `entityReferenceMap`
- There was an issue with resource links being wrongly detected as normal …
> fix: circular references and infinite loop problems

- README.md
- package.json
- packages/live-preview-sdk/package.json
As we don't use any react 18 specific code, there speaks nothing against adding version 17 of react to the peer dependencies
> chore: allow react 17 for peerDependencies

- packages/live-preview-sdk/src/__tests__/inspectorMode.spec.ts
- packages/live-preview-sdk/src/__tests__/liveUpdates.spec.ts
- packages/live-preview-sdk/src/__tests__/validateMessages.spec.ts
- packages/live-preview-sdk/src/constants.ts
- packages/live-preview-sdk/src/helpers/utils.ts
- packages/live-preview-sdk/src/helpers/validateMessage.ts
- packages/live-preview-sdk/src/index.ts
- packages/live-preview-sdk/src/inspectorMode.ts
- packages/live-preview-sdk/src/liveUpdates.ts
- packages/live-preview-sdk/src/messages.ts
- packages/live-preview-sdk/src/types.ts
- packages/visual-sdk/src/index.ts
Extract the enum for the Post Messages and the correlated message types from './types' as a `enum` is technically more than a type and to be able to easily share them
Optimizes also the exports so you don't need to import from 'dist/types' anymore
> fix(types): optimize export of typings

- packages/live-preview-sdk/src/index.ts
- packages/live-preview-sdk/src/inspectorMode.ts
- packages/live-preview-sdk/src/messages.ts
`this.inspectorMode?.getTaggedElements()` as the inspectorMode could be undefined, we don't always send the tagged elements and therefore the analytics for the statusmodal can be faulty.
> fix(live-preview): adjust missing data for the status modal

- README.md
- packages/live-preview-sdk/src/index.ts
- packages/live-preview-sdk/src/inspectorMode.ts
- packages/live-preview-sdk/src/messages.ts
Exposing and decoupling the logic for opening an entry in the Contentful UI from the specific inspector mode class
> feat: expose opening entry [TOL-1237]

- examples/nextjs-graphql/lib/api-graphql.ts
- examples/nextjs-graphql/package.json
- examples/nextjs-graphql/pages/_app.tsx
- examples/nextjs-graphql/pages/posts/[slug].tsx
- packages/live-preview-sdk/src/graphql/__tests__/queryUtils.test.ts
- packages/live-preview-sdk/src/graphql/entries.ts
- packages/live-preview-sdk/src/graphql/queryUtils.ts
- packages/live-preview-sdk/src/graphql/utils.ts
- packages/live-preview-sdk/src/helpers/resolveReference.ts
The typename for fields inside a collection was not correctly generated, and therefore they were not identified correctly and in `isRelevantField` they were ignored.
We now generate the typename correctly instead of  `items`, which enables updates again.
Migrated the nextjs-graphql example to use graphql-request and GraphQL Documents, which allows us to also demo the usage with a provided query
> fix(graphql): providing the query no longer prevents updates [TOL-1409]

- examples/next-13-app-router-graphql/app/layout.tsx
- examples/next-13-app-router-graphql/package.json
Hi there,
I am currently setting up the live preview mode for Contentful. The `live-updates` are working, but the inspector mode was missing the css import in the next 13 example app:
https://github.com/contentful/live-preview/tree/main/examples/next-13-app-router-graphql
I have also deleted the `globals.css` and the `prepare` step in the package.json, since they where both unused and preventing the app from starting.
:v:
> fix(example): next 13 with app router

- packages/live-preview-sdk/src/constants.ts
- packages/live-preview-sdk/src/helpers/utils.ts
Improving security of postMessages going into editor.
> feat: [] Add origins for editor postMessage

- packages/live-preview-sdk/src/liveUpdates.ts
- packages/live-preview-sdk/src/rest/__tests__/entities.test.ts
- packages/live-preview-sdk/src/rest/entities.ts
- packages/live-preview-sdk/src/rest/index.ts
For circular references we were getting links instead of resolved entities when the same references is linked twice in the page
> fix: fixing circular ref updates by using store of already fetched data []

- .circleci/config.yml
- .gitignore
- README.md
- examples/next-13-app-router-ssr/README.md
- examples/next-13-app-router-ssr/package.json
- packages/live-preview-sdk/src/__tests__/inspectorMode.spec.ts
- packages/live-preview-sdk/src/__tests__/liveUpdates.spec.ts
- packages/live-preview-sdk/src/__tests__/react.spec.tsx
- packages/live-preview-sdk/src/__tests__/resolveReference.spec.ts
- packages/live-preview-sdk/src/constants.ts
- packages/live-preview-sdk/src/graphql/__tests__/entries.test.ts
- packages/live-preview-sdk/src/graphql/entries.ts
- packages/live-preview-sdk/src/helpers/resolveReference.ts
- packages/live-preview-sdk/src/helpers/utils.ts
- packages/live-preview-sdk/src/index.ts
- packages/live-preview-sdk/src/inspectorMode.ts
- packages/live-preview-sdk/src/liveUpdates.ts
- packages/live-preview-sdk/src/messages.ts
- packages/live-preview-sdk/src/react.tsx
- packages/live-preview-sdk/src/rest/__tests__/entities.test.ts
- packages/live-preview-sdk/src/rest/entities.ts
- packages/live-preview-sdk/src/types.ts
Allow overriding the targetOrigin which is used to restrict the messaging between contentful and this SDK.
Currently, we're always sending it to app.contentful.com and app.eu.contentful.com, which produces an error for each message in the console.
Developers setting up the SDK can not configure it only for one instance of contentful and don't get the misleading errors anymore.
Why do we need both parameters then?
Removing them and using only one would be a breaking change
> fix: allow overriding the targetOrigin for messaging []

- packages/visual-sdk/src/store/EditorEntityStore.ts
- packages/visual-sdk/src/store/EditorStore.spec.ts
- packages/visual-sdk/src/store/EntityStore.ts
Entry and Asset can have the same ID, therefore we should split up the entities into two maps (one for asset, one for entry)
> fix(entity-store): split into asset and entry map to prevent id collision

- packages/visual-sdk/src/store/EditorEntityStore.ts
Currently, a timed out request is kept in the request cache. So when we retry it, we directly get the same error again.
> fix: cleanup request cache after timeout [SPA-1711]

- packages/visual-sdk/src/store/EditorEntityStore.ts
When there are invalid links in the experience, then the visual SDK will currently not accept the `REQUESTED_ENTITIES` message. By passing the list of "failed" entity IDs, the recognition logic should be working for these edge cases as well.
Example messages when it failed:
> fix: accept message when missing entity IDs are matching as well  [SPA-1711] [SPA-1673]

- .gitignore
- packages/live-preview-sdk/package.json
- packages/live-preview-sdk/src/__tests__/csm.spec.ts
- packages/live-preview-sdk/src/csm/index.ts
- packages/live-preview-sdk/src/csm/types.ts
Transform Content Source Maps (CSM) from the GraphQL API into hidden encoded strings. Only fields that are not evaluated as URL or ISO Date.
> feat: implement CSM transformation to encoded strings for GraphQL [TOL-1706]

- .eslintrc.cjs
- packages/live-preview-sdk/src/__tests__/react.spec.tsx
- packages/live-preview-sdk/src/inspectorMode/__tests__/getAllTaggedElements.test.ts
- packages/live-preview-sdk/src/inspectorMode/index.ts
- packages/live-preview-sdk/src/inspectorMode/utils.ts
- packages/live-preview-sdk/vite.config.ts
Small cleanup:
- Suppress expected errors from test log
- Added tests for `getAllTaggedElements` and added checking for proper attributes there.
- Used `TreeWalker` for a faster & more flexible document scanning. 
- Random fixes
I opened this to keep the follow up PR small. There should be **no behavioral** change with this PR.
> refactor: small clean up and adding tests

- packages/live-preview-sdk/src/__tests__/csm.spec.ts
- packages/live-preview-sdk/src/csm/encode.ts
- packages/live-preview-sdk/src/csm/index.ts
- packages/live-preview-sdk/src/index.ts
- packages/live-preview-sdk/src/inspectorMode/__tests__/getAllTaggedElements.test.ts
- packages/live-preview-sdk/src/inspectorMode/index.ts
- packages/live-preview-sdk/src/inspectorMode/utils.ts
- Detect hidden strings in a page and convert it to proper data attributes.
- Note that this doesn't care about whether a parent element is manually tagged or not.
- Adds a flag to ignore existing manual attributes for testing purposes.
> feat: recognise auto-tagged elements [TOL-1711]

- .circleci/config.yml
- .contentful/vault-secrets.yaml
- .eslintrc.cjs
- .github/dependabot.yml
- catalog-info.yaml
- examples/next-13-app-router-ssr/package.json
- package.json
- packages/live-preview-sdk/CHANGELOG.md
- packages/live-preview-sdk/catalog-info.yaml
- packages/live-preview-sdk/package.json
- packages/live-preview-sdk/src/__tests__/csm.spec.ts
- packages/live-preview-sdk/src/__tests__/react.spec.tsx
- packages/live-preview-sdk/src/__tests__/validation.spec.ts
- packages/live-preview-sdk/src/csm/encode.ts
- packages/live-preview-sdk/src/csm/index.ts
- packages/live-preview-sdk/src/csm/types.ts
- packages/live-preview-sdk/src/helpers/utils.ts
- packages/live-preview-sdk/src/helpers/validation.ts
- packages/live-preview-sdk/src/index.ts
- packages/live-preview-sdk/src/inspectorMode/__tests__/getAllTaggedElements.test.ts
- packages/live-preview-sdk/src/inspectorMode/index.ts
- packages/live-preview-sdk/src/inspectorMode/utils.ts
- packages/live-preview-sdk/src/react.tsx
- packages/live-preview-sdk/vite.config.ts
- yarn.lock
> feat: export csm

- packages/live-preview-sdk/src/__tests__/csm.spec.ts
- packages/live-preview-sdk/src/csm/encodeSourceMap.ts
- packages/live-preview-sdk/src/csm/index.ts
- packages/live-preview-sdk/src/inspectorMode/utils.ts
- add comments to explain how `getAllTaggedElements` works. This code was confusing me a lot and I hope this could help in the future.
- renamed `encodeSourceMap` to `encodeGraphQLResponse`
- exported `encode` and `decode` since we need it in the webapp when making live updates with CSM
> chore: export CSM utils

- package.json
- packages/content-source-maps/package.json
- packages/content-source-maps/tsconfig.json
- packages/content-source-maps/vite.config.ts
- packages/live-preview-sdk/package.json
- packages/live-preview-sdk/src/helpers/utils.ts
- packages/live-preview-sdk/src/index.ts
- packages/live-preview-sdk/src/inspectorMode/__tests__/getAllTaggedElements.test.ts
- packages/live-preview-sdk/src/inspectorMode/utils.ts
- yarn.lock
Our exports weren't correctly configured so as a result when we imported from the csm package in LP we would get an error which didn't break the CI. This was now affecting the stability cleanup PR
- We have set up the build & export config to match the LP SDK
- we have also added a fix for handling graqhpl queries are passed as strings
> chore: update build config to fix cjs issues in LP []

- packages/live-preview-sdk/src/__tests__/index.spec.ts
- packages/live-preview-sdk/src/__tests__/react.spec.tsx
- packages/live-preview-sdk/src/index.ts
- packages/live-preview-sdk/src/inspectorMode/index.ts
- packages/live-preview-sdk/src/inspectorMode/types.ts
- packages/live-preview-sdk/src/inspectorMode/utils.ts
- packages/live-preview-sdk/src/messages.ts
- packages/live-preview-sdk/src/react.tsx
- packages/live-preview-sdk/src/types.ts
Add the ability to add space and environment for inspectorMode attributes.
For the CSM they are automatically picked up
Closes #526
> feat(inspectorMode): support tagging for cross space references []

- packages/live-preview-sdk/src/inspectorMode/__tests__/getAllTaggedElements.test.ts
- packages/live-preview-sdk/src/inspectorMode/utils.ts
Optimize tagging for images with `<picture>` or `<figure>`
> fix(inspectorMode): img tagging with CSM []

- packages/content-source-maps/src/__tests__/csm.spec.ts
- packages/content-source-maps/src/encodeSourceMap.ts
Array of symbol (list) field was not working properly with CSM. We now handle it by looping over every item in the array and adding the encoding to each item.
> fix: array symbol field csm [TOL-1845]

- packages/live-preview-sdk/src/index.ts
When debugging customers issues we run the webapp locally. We need to allow the targetOrigin to be localhost otherwise live preview will not function.
> feat: localhost allowed origin

- packages/content-source-maps/src/__tests__/csm.spec.ts
- packages/content-source-maps/src/encode.ts
- packages/content-source-maps/src/encodeSourceMap.ts
- packages/content-source-maps/src/richText.ts
- packages/content-source-maps/src/types.ts
- packages/content-source-maps/src/utils.ts
- packages/live-preview-sdk/src/inspectorMode/__tests__/fixtures/contentSourceMap.ts
The editor interface / field appearance of a field should determine if we generate hidden strings from the CSM for that field.
We return the editor interface as part of the CSM API GraphQL response and now have to filter it out in the SDK. This could enable future configuration for the user on the frontend side (e.g. they do want to add hidden strings to dropdown).
- For symbol fields only create hidden strings in the SDK for the single line editor interface
- For short text list fields, we create hidden strings for all of them:
- For Rich text we always generate hidden strings
- For long text we generate hidden strings for single line, multiple line and markdown
> feat: support editor interface and field types for CSM [TOL-1836]

- examples/next-14-app-router-ssr/app/api/revalidate/route.ts
- examples/next-14-app-router-ssr/public/_live-preview.ts
Refreshing window instead of calling redirect
Redirect doesn't appear to work here, and I don't believe refreshing the page is that bad.
Maybe this is relevant: https://github.com/vercel/next.js/issues/59489
> fix: refreshing page instead of redirect []

- packages/live-preview-sdk/src/index.ts
as part of [this](https://contentful.atlassian.net/browse/TOL-2080?atlOrigin=eyJpIjoiZjIyOWNkYmEwZGE5NDIyYTlhZmE4YTBjZTc2MDQwOWUiLCJwIjoiaiJ9) we are now removing the encodeCPAResponse export from the LP SDK
> feat: remove encode from cpa export

- packages/live-preview-sdk/src/index.ts
Re-exporting `encodeCPAResponse` for customers hitting the CPA directly (instead of using the JS Client SDK) and wanting to use encoding.
> feat: export cpa response

- packages/content-source-maps/src/__tests__/encode.spec.ts
We're incorporating unit tests to identify which date formats the vercel/stega package can encode and which it cannot. These tests will help prevent regressions and also act as reference documentation for our team.
> test: encoding of date format [TOL-2120]

- examples/content-source-maps-cpa/package.json
- examples/content-source-maps-graphql/package.json
Updating to the latest SDK version so we can support the new Content Source Maps format coming from the API in the examples
> docs: update examples sdk version [TOL-2193]

- catalog-info.yaml
thought it would be better directed here than to the default channel
https://contentful.slack.com/archives/C04LSEF4R2R/p1718964303895699
> chore: add ci alerts []

- packages/content-source-maps/src/__tests__/graphql.spec.ts
- packages/content-source-maps/src/__tests__/rest.spec.ts
- packages/content-source-maps/src/graphql/encodeGraphQLResponse.ts
- packages/content-source-maps/src/rest/encodeCPAResponse.ts
- packages/content-source-maps/src/types.ts
- packages/content-source-maps/src/utils.ts
- packages/live-preview-sdk/src/inspectorMode/__tests__/fixtures/contentSourceMap.ts
- packages/live-preview-sdk/src/inspectorMode/utils.ts
Provides the ability to reduce the payload of the hidden strings if only one platform for previewing is used
- using `contentful` - removing the `href` property
- using `vercel` - removing the `contentful` property
> feat(content-source-maps): allow specify a platform to reduce the payload []

- packages/content-source-maps/src/__tests__/graphql.spec.ts
- packages/content-source-maps/src/__tests__/rest.spec.ts
- packages/content-source-maps/src/utils.ts
Adding support for longText field type, but not the markdown widget type
> feat: support long text for csm [TOL-2269]

- packages/live-preview-sdk/package.json
testing 4.3.0-alpha.6 revealed that we still need the react export in the package.json
> chore: test out new swc config with react export

- packages/live-preview-sdk/src/inspectorMode/__tests__/getAllTaggedElements.test.ts
- packages/live-preview-sdk/src/inspectorMode/utils.ts
Auto-tag all block based elements in rich text instead of just the parent wrapper rich text element
> fix: rich text block based auto tagging [TOL-2101]

- packages/content-source-maps/src/__tests__/graphql.spec.ts
- packages/content-source-maps/src/__tests__/rest.spec.ts
- packages/content-source-maps/src/utils.ts
Add a `?source=vercel-content-link` query param to the URL when users are clicking on ‘Open in Contentful’ link in the Vercel Visual Editor
> feat: add vercel tracking query param [TOL-1916]

- packages/live-preview-sdk/src/inspectorMode/__tests__/addCalculatedAttributesToTaggedElements.test.ts
- packages/live-preview-sdk/src/inspectorMode/index.ts
- packages/live-preview-sdk/src/inspectorMode/utils.ts
Checking intersections of overlapping tagged elements and adding an attribute which is sent to the editor to stop rendering tagged elements which should be hidden.
- For each 4 corners of the tagged elements calculate what the topmost element is at that point
- If the topmost element is not the tagged element add property to hide tagged element
> fix: adding new property to tagged elements that are overlapped by others [TOL-2408]

- packages/live-preview-sdk/src/__tests__/index.spec.ts
- packages/live-preview-sdk/src/__tests__/init.spec.ts
- packages/live-preview-sdk/src/__tests__/react.spec.tsx
- packages/live-preview-sdk/src/index.ts
- packages/live-preview-sdk/src/inspectorMode/__tests__/getAllTaggedElements.bench.ts
- packages/live-preview-sdk/src/inspectorMode/__tests__/getAllTaggedElements.test.ts
- packages/live-preview-sdk/src/inspectorMode/utils.ts
- packages/live-preview-sdk/src/liveUpdates.ts
- packages/live-preview-sdk/src/react.tsx
Makes debug messaging more explicit and meaningful, so as to make configuration issues and user debugging easier
> fix: improve error messaging

- packages/content-source-maps/src/__tests__/encode.spec.ts
- packages/content-source-maps/src/__tests__/graphql.spec.ts
- packages/content-source-maps/src/__tests__/rest.spec.ts
- packages/content-source-maps/src/graphql/encodeGraphQLResponse.ts
- packages/content-source-maps/src/types.ts
- packages/content-source-maps/src/utils.ts
- packages/live-preview-sdk/src/index.ts
- packages/live-preview-sdk/src/inspectorMode/__tests__/fixtures/contentSourceMap.ts
- packages/live-preview-sdk/src/inspectorMode/__tests__/getAllTaggedElements.bench.ts
- packages/live-preview-sdk/src/inspectorMode/__tests__/getAllTaggedElements.test.ts
- packages/live-preview-sdk/src/inspectorMode/__tests__/parseAttributesFromHref.test.ts
- packages/live-preview-sdk/src/inspectorMode/utils.ts
- Remove redundant info from hidden sourcemaps. We can determine the properties based on the Contentful HREF param and remove them from `contentful` object. This means that HREF param should now always be present, even if the platform is set to 'contentful'. Previously we only used the HREF param for Vercel Content Link. The code is still backwards compatible.
- Fix typescript issues: https://github.com/contentful/live-preview/issues/924
> fix: remove redundant contentful info CSM [NONE]

- packages/live-preview-sdk/src/liveUpdates.ts
Reverts changes applied in: https://github.com/contentful/live-preview/pull/893
We were incorrectly assuming that sys.id would always be present on `data`
But for GraphQL, `data` could also look like this:
```
{ "postCollection": { "items": [ { "__typename": "Post", "sys": { "id": "a1b2c3" }, "slug": "foo", "title": "new value​​​​‌﻿‍﻿​‍​‍‌‍﻿﻿‌﻿​‍‌‍‍‌‌‍‌﻿‌‍‍‌‌‍﻿‍​‍​‍​﻿‍‍​‍​‍‌‍​﻿‌‍﻿﻿‌‍﻿‍‌﻿‌​‌‍‌‌‌‍﻿‍‌﻿‌​‌‍‌‍‌﻿‌‌‌‍﻿​​‍﻿‍‌‍​﻿‌‍﻿﻿‌‍﻿‌​‍​‍​‍﻿​​‍​‍‌‍‍​‌﻿​‍‌‍‌‌‌‍‌‍​‍​‍​﻿‍‍​‍​‍‌‍‍​‌﻿‌​‌﻿‌​‌﻿​​‌﻿​﻿​﻿‍‍​‍﻿﻿​‍﻿﻿‌‍​‌‌﻿​​‌﻿​​​‍﻿‍‌‍​﻿‌‍﻿﻿‌‍﻿‍‌﻿‌​‌‍‌‌‌‍﻿‍‌﻿‌​‌‍‌‍‌﻿‌‌‌‍﻿​​‍﻿‍‌‍​﻿‌‍﻿﻿‌‍﻿‌​‍﻿﻿‌﻿​﻿‌﻿​​‌‍​‌‌‍​﻿‌‍‌‌‌﻿​﻿​‍﻿﻿‌﻿‌​‌‍‌‌‌﻿​﻿‌﻿‌​​‍﻿‌‌﻿​﻿‌﻿​​‌‍​‌‌‍​﻿‌‍‌‌​‍﻿﻿‌‍‌‌‌‍﻿‍‌﻿‌‍‌‍‍‌‌﻿​‍‌‍﻿﻿‌‍﻿‍‌‍﻿‌‌‍‌‌‌‍﻿‍‌﻿‌​‌﻿​﻿​‍﻿﻿‌‍﻿‌‌‍​‌‌﻿​﻿‌﻿‌​‌‍‌‌‌﻿​‍​‍﻿﻿‌‍‌‌‌‍﻿‍‌﻿‌​‌﻿​‍‌‍‍‌‌‍‌‌‌﻿​﻿​‍﻿﻿‌‍​‌​﻿​‌‌‍​‍​﻿​‍‌‍​﻿​﻿​﻿​‍﻿﻿​﻿﻿﻿‌‍‌‍ …
```
> fix: remove wrong sys check [NONE]

- packages/live-preview-sdk/src/inspectorMode/utils.ts
- Not hiding elements that share borders
- Fixing hiding logic
> fix: not hiding elements that share borders [TOL-2545]

- packages/live-preview-sdk/package.json
- packages/live-preview-sdk/vite.config.ts
- yarn.lock
Second attempt to support react 19 and Next 15. The previous PR (https://github.com/contentful/live-preview/pull/980) caused issues in projects using Next.js 14. The following issue appeared:
The current build config only marks 'react' as external, but now we also mark the other React submodules.
> feat: support react 19

- packages/content-source-maps/src/richText.ts
When encoding rich text fields, undefined values could be introduced into the `contentSourceMaps.mappings` object, causing serialisation errors in Next.js getStaticProps.
> fix: undefined mappings in csm [TOL-2540]

- packages/content-source-maps/src/rest/encodeCPAResponse.ts
Sometimes, entries will not respond with `contentSourceMaps` under `sys`, if they for example only have one field type that is not supported with content source maps. We should not throw an error in this case, but just return as normal
For example in this case we have an entry with only one field type (markdown) and no content source maps:
> fix: do not error when no source maps []
